"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class payload_comp_msg_t(object):

    __slots__ = ["cam_enabled", "exp_enabled"]

    __typenames__ = ["boolean", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.cam_enabled = False
        """ LCM Type: boolean """
        self.exp_enabled = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(payload_comp_msg_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.cam_enabled, self.exp_enabled))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != payload_comp_msg_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return payload_comp_msg_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = payload_comp_msg_t()
        self.cam_enabled = bool(struct.unpack('b', buf.read(1))[0])
        self.exp_enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if payload_comp_msg_t in parents: return 0
        tmphash = (0xa194ba54e9f35b2f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if payload_comp_msg_t._packed_fingerprint is None:
            payload_comp_msg_t._packed_fingerprint = struct.pack(">Q", payload_comp_msg_t._get_hash_recursive([]))
        return payload_comp_msg_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", payload_comp_msg_t._get_packed_fingerprint())[0]

