"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class payload_cont_to_cam_msg_t(object):

    __slots__ = ["cont_state", "debug_mode"]

    __typenames__ = ["int8_t", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.cont_state = 0
        """ LCM Type: int8_t """
        self.debug_mode = False
        """
        change to contain numbers 1 to 8 (enums)
        LCM Type: boolean
        """


    def encode(self):
        buf = BytesIO()
        buf.write(payload_cont_to_cam_msg_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.cont_state, self.debug_mode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != payload_cont_to_cam_msg_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return payload_cont_to_cam_msg_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = payload_cont_to_cam_msg_t()
        self.cont_state = struct.unpack(">b", buf.read(1))[0]
        self.debug_mode = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if payload_cont_to_cam_msg_t in parents: return 0
        tmphash = (0x8e6ada26b8d053e5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if payload_cont_to_cam_msg_t._packed_fingerprint is None:
            payload_cont_to_cam_msg_t._packed_fingerprint = struct.pack(">Q", payload_cont_to_cam_msg_t._get_hash_recursive([]))
        return payload_cont_to_cam_msg_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", payload_cont_to_cam_msg_t._get_packed_fingerprint())[0]

