"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class cam_msg_t(object):

    __slots__ = ["cam_calib_complete", "exp_complete"]

    __typenames__ = ["boolean", "boolean"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.cam_calib_complete = False
        """ LCM Type: boolean """
        self.exp_complete = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(cam_msg_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.cam_calib_complete, self.exp_complete))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_msg_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_msg_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = cam_msg_t()
        self.cam_calib_complete = bool(struct.unpack('b', buf.read(1))[0])
        self.exp_complete = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if cam_msg_t in parents: return 0
        tmphash = (0xb96f7b46cac246b9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if cam_msg_t._packed_fingerprint is None:
            cam_msg_t._packed_fingerprint = struct.pack(">Q", cam_msg_t._get_hash_recursive([]))
        return cam_msg_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cam_msg_t._get_packed_fingerprint())[0]

